### ISSUE TITLE
在webqsp上训练NSM出错

### ISSUE THREAD

**Issue by 2213500360** [RUCKBReasoning/SubgraphRetrievalKBQA#2]
您好！感谢提供代码！ 我想要运行您提供的NSM代码但出现了一些问题：
首先下载了您提供的google drive上的预处理后的数据集，将其解压以后，将run_webqsp.sh中的--data_folder 参数更改为该解压文件夹。但在我首次运行时报错，错误信息显示--checkpoint_dir 的文件夹不存在，于是我新建里一个文件夹num_point并更改了--checkpoint_dir。 
更改后程序成功运行了，但是训练过程好像出现了错误：
![222](https://user-images.githubusercontent.com/67719519/159956147-609fb0eb-3b7c-42c7-91e8-2c12a21faea0.png)
如上图，程序似乎完全没有在训练，并且在epoch到达200时报错：
![2222](https://user-images.githubusercontent.com/67719519/159956489-2cf86117-f816-4934-8794-5d24dbe90571.png)
我想我可能哪里设置错了或者忘记下载了什么文件，请问您知道原因吗

**Comment by FH-xk** [comment]
I also met the same problem, hope the author can solve the confusion, in addition, you solved this problem

**Comment by FH-xk** [comment]
I have also encountered the same problem, I hope the author can solve my confusion, in addition, I would like to ask you to solve this problem

**Comment by DuanyangYuan** [comment]
Hello, I have the following error when running run_retrieve_subgraph.py. Do you encounter it?
Traceback (most recent call last):
File "/home/horanchen/ydy/study/code/SubgraphRetrievalKBQA-main/src/run_retrieve_subgraph.py", line 9, in
run()
File "/home/horanchen/ydy/study/code/SubgraphRetrievalKBQA-main/src/run_retrieve_subgraph.py", line 5, in run
run_retrieve_subgraph()
File "/home/horanchen/ydy/study/code/SubgraphRetrievalKBQA-main/src/retrieve_subgraph/retrieve_subgraph.py", line 282, in run
train_dataset = load_jsonl(os.path.join(load_data_folder, "train_simple.json"))
File "/home/horanchen/ydy/study/code/SubgraphRetrievalKBQA-main/src/utils.py", line 8, in load_jsonl
data_list.append(json.loads(line))
File "/home/horanchen/anaconda3/envs/sugkbqa/lib/python3.10/json/init.py", line 346, in loads
return _default_decoder.decode(s)
File "/home/horanchen/anaconda3/envs/sugkbqa/lib/python3.10/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/home/horanchen/anaconda3/envs/sugkbqa/lib/python3.10/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 177891 (char 177890)
