### ISSUE TITLE
Error when executing 'run_train_nsm.py' for CWQ

### ISSUE THREAD

**Issue by luojintao** [RUCKBReasoning/SubgraphRetrievalKBQA#6]
![image](https://user-images.githubusercontent.com/57553975/196978643-5ecaa687-92c8-4ba5-a214-48888f91db29.png)

It looks like the CWQ dataset is missing some files.
![image](https://user-images.githubusercontent.com/57553975/196979102-7a73337d-c69f-41e1-a574-db588802cabb.png)

Could you please add to this, thank you very much!!!

**Comment by lambdaDove** [comment]
These missing files can be found in the 'main' branch. I will fix it soon~

**Comment by luojintao** [comment]
> These missing files can be found in the 'main' branch. I will fix it soon~

Thank you very much for your reply!
I added these missing data from the ‘main’ branch.
![image](https://user-images.githubusercontent.com/57553975/197127528-eef53b95-b0e6-495e-a4a4-377e1ec2f234.png)
But a new problem emerged：
![image](https://user-images.githubusercontent.com/57553975/197128043-9f270360-dd11-42a5-a42d-6fae026e7fff.png)
It seems that some files are missing here.
![image](https://user-images.githubusercontent.com/57553975/197128243-ee946109-b301-4d9c-95ac-426aba63140e.png)

**Comment by lambdaDove** [comment]
OK. I will check the data folder from that google drive link. 
Files like 'vocab_new.txt' are inherited from the original NSM to initialize the word embedding for the LSTM module. It's the same as WebQSP setting.

**Comment by luojintao** [comment]
I have added the relevant data, but it still does not work. Maybe you have modified the data and code? Could you please upload the complete code and data for the CWQ dataset and describe the process in the README?

**Comment by lambdaDove** [comment]
[this](https://drive.google.com/file/d/1QkMFC7lgD7do9eWBDoF-ctEBEKvSS2Jt/view?usp=sharing) contains most of the code for CWQ. Thanks for your advice,Thank you for your suggestion, I will update CWQ's branch.

**Comment by luojintao** [comment]
It looks like you converted the entities to integers, can I get files on that?

**Comment by lambdaDove** [comment]
> It looks like you converted the entities to integers, can I get files on that?

Of course, give me some time and I will provide you with a dict file saved with the suffix pickle that you can load using pickle in Python. Please use this [ent2id.pickle](https://drive.google.com/file/d/1tPnzs2ZcronEO-n9Jk6BLxp38rgu7NLo/view)

**Comment by luojintao** [comment]
> It looks like the CWQ dataset is missing some files. ![image](https://user-images.githubusercontent.com/57553975/196979102-7a73337d-c69f-41e1-a574-db588802cabb.png)
> 
> Could you please add to this, thank you very much!!!

 Due to the different data formats (e.g. in CWQ/tmp/reader_data/CWQ/dev_sample.json and tmp/reader_data/webqsp/dev_sample.json), the NSM code should be different for the webqsp and cwq datasets.

Copying NSM code directly from webqsp to CWQ is not available. Can you please share the code for CWQ?

**Comment by DuanyangYuan** [comment]
Hello, I have the following error when running run_retrieve_subgraph.py. Do you encounter it?
Traceback (most recent call last):
File "/home/horanchen/ydy/study/code/SubgraphRetrievalKBQA-main/src/run_retrieve_subgraph.py", line 9, in
run()
File "/home/horanchen/ydy/study/code/SubgraphRetrievalKBQA-main/src/run_retrieve_subgraph.py", line 5, in run
run_retrieve_subgraph()
File "/home/horanchen/ydy/study/code/SubgraphRetrievalKBQA-main/src/retrieve_subgraph/retrieve_subgraph.py", line 282, in run
train_dataset = load_jsonl(os.path.join(load_data_folder, "train_simple.json"))
File "/home/horanchen/ydy/study/code/SubgraphRetrievalKBQA-main/src/utils.py", line 8, in load_jsonl
data_list.append(json.loads(line))
File "/home/horanchen/anaconda3/envs/sugkbqa/lib/python3.10/json/init.py", line 346, in loads
return _default_decoder.decode(s)
File "/home/horanchen/anaconda3/envs/sugkbqa/lib/python3.10/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/home/horanchen/anaconda3/envs/sugkbqa/lib/python3.10/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 177891 (char 177890)

**Comment by Ioveffffff** [comment]
![image](https://github.com/user-attachments/assets/f18d1144-feab-42c6-8991-42578d17b966)
Can you provide this package, some of the files in the original author's google for this package are no longer available
